# Build documentation in the docs/ directory with Sphinx
version: 2

sphinx:
  configuration: docs/conf.py

conda:
  environment: environment.yml

python:
  version: 3.6
  install:
    - method: pip
    - path: .
      extra_requirements:
        - testing
        - docs