matrix:
  include:
    - os: osx
      langauge: sh
      env: PYTHON="3.6"
    - os: osx
      langauge: sh
      env: PYTHON="3.7"
    - os: linux
      dist: xenial
      language: python
      env: PYTHON="3.7"
    - os: linux
      dist: xenial
      language: python
      env: PYTHON="3.7"

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda;
  - export PATH="$HOME/miniconda/bin:$PATH";
  - hash -r;
  - conda config --set always_yes yes --set changeps1 no;
  - conda update -q conda;
  - conda create -n myenv python=$PYTHON anaconda;
  - source activate myenv;
  - conda install -c conda-forge cyipopt;
install:
  - python -m pip install .[all]
script:
  - PYTHONPATH=$(pwd) python -m pytest --pep8 --ignore setup.py --ignore build/
notifications:
  email: false