matrix:
  include:
    - os: osx
      langauge: sh
      env: PYTHON="3.6"
    - os: osx
      langauge: sh
      env: PYTHON="3.7"
    - os: linux
      dist: xenial
      language: python
      env: PYTHON="3.6"
    - os: linux
      dist: xenial
      language: python
      env: PYTHON="3.7"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda;
  - source $HOME/miniconda/etc/profile.d/conda.sh;
  - hash -r;
  - conda config --set always_yes yes --set changeps1 no;
  - conda update -q conda;
install:
  - conda create -n symopt python=$PYTHON anaconda;
  - conda activate symopt;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      conda install gfortran_osx-64;
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install gfortran;
    fi
  - conda install -c conda-forge cyipopt;
  - python -m pip install .[all]
script:
  - PYTHONPATH=$(pwd) python -m pytest --pep8 --ignore setup.py --ignore build/
notifications:
  email: false